### ISSUE TITLE
Add team member photos

### ISSUE THREAD

**Issue by damithc** [CS2103AUG2016-T15-C4/main#51]
Some of your team member photos are missing from AboutUs.md. Please update or there will be a penalty. The purpose of the photo is to identify you, so please ensure the photo is suitable for that purpose.
![image](https://cloud.githubusercontent.com/assets/1673303/19555768/d47a20ee-96f0-11e6-9911-6c3bf86a7f51.png)

**Comment by JamesHuangUC** [comment]
@mchen14 @A0116137M
